#!/usr/bin/python

"""
Python module defining radiometers

Usage:
from radiometer_define import sat_sen
"""

# Satellite/Sensor Properties - define the sensors, the satellites that carry them, and 
# their channel characteristics.
full_sat_sen = {
           'wndmi': { 'sat' : ['CORIOL',],
                    'inst': '201',
                    'beam_positions': int(80),
                    'freq': {'1':'6.8 GHz V',
                             '2':'6.8 GHz H',
                             '3':'10.7 GHz V',
                             '4':'10.7 GHz H',
                             '5':'10.7 GHz U',
                             '6':'10.7 GHz F',
                             '7':'18.7 GHz V',
                             '8':'18.7 GHz H',
                             '9':'18.7 GHz U',
                             '10':'18.7 GHz F',
                             '11':'23.8 GHz V',
                             '12':'23.8 GHz H',
                             '13':'37.0 GHz V',
                             '14':'37.0 GHz H',
                             '15':'37.0 GHz U',
                             '16':'37.0 GHz F'}
                  },
 
           'amsr2': { 'sat' : ['GCOMW1',],
                    'inst': '200',
                    'beam_positions': int(223),
                    'freq': {'1':'6 GHz V',
                             '2':'6 GHz H',
                             '3':'7 GHz V',
                             '4':'7 GHz H',
                             '5':'10 GHz V',
                             '6':'10 GHz H',
                             '7':'18 GHz V',
                             '8' :'18 GHz H',
                             '9' :'23 GHz V',
                             '10':'23 GHz H',
                             '11':'36 GHz V',
                             '12':'36 GHz H',
                             '13':'89 GHz V',
                             '14':'89 GHz H'}
                  },
           'saphir': { 'sat' : ['Megha-Tropiques',],
                    'inst': '199',
                    'beam_positions': int(182),
                    'freq': {'1':'183.31+/-0.2 GHz H',
                             '2':'183.31+/-1.1 GHz H',
                             '3':'183.31+/-2.8 GHz H',
                             '4':'183.31+/-4.2 GHz H',
                             '5':'183.31+/-6.8 GHz H',
                             '6':'183.31+/-11.0 GHz H'}
                  },
           'gmi': { 'sat' : ['GPM',],
                    'inst': '198',
                    'beam_positions': int(221),
                    'freq': {'1':'10.65 GHz V',
                             '2':'10.65 GHz H',
                             '3':'18.7 GHz V',
                             '4':'18.7 GHz H',
                             '5':'23.8 GHz V',
                             '6':'36.64 GHz V',
                             '7':'36.64 GHz H',
                             '8':'89.0 GHz V',
                             '9':'89.0 GHz H',
                             '10':'166.0 GHz V',
                             '11':'166.0 GHz H',
                             '12':'183.31+/-3.0 GHz',
                             '13':'183.31+/-7.0 GHz'}
                  },
           'geo_csr': {   'sat' :  ['MTP-07', 'MSG-08', 'MSG-09', 'MSG-10', 'MSG-11', \
                                    'COMS-1', 'MTSAT2', 'HIMA08', 'HIMA09', \
                                    'GOES13', 'GOES15', 'GOES16', 'GOES17'], 
                        'inst' : '194',
              'beam_positions' : None,
                     'geo_lon' : { 'MTP-07' : float(57.3), 
                                   'MSG-08' : float(41.5),
                                   'MSG-10' : float(0),
                                   'MSG-11' : float(0),
                                   'COMS-1' : float(128.2),
                                   'GOES13' : float(-75),
                                   'GOES15' : float(-135),
                                   'GOES16' : float(-75),
                                   'GOES17' : float(-135),
                                   'HIMA08' : float(145),
                                   'HIMA09' : float(145),
                                   'MTSAT2' : float(145)},
                       'MTP-07' : 'MVIRI',
                       'MSG-08' : 'SEVIRI',
                       'MSG-09' : 'SEVIRI',
                       'MSG-10' : 'SEVIRI',
                       'MSG-11' : 'SEVIRI',
                       'COMS-1' : 'MI',
                       'GOES13' : 'GOES_Imager',
                       'GOES15' : 'GOES_Imager',
                       'GOES16' : 'ABI',
                       'GOES17' : 'ABI',
                       'MTSAT2' : 'MT2_Imager',
                       'HIMA08' : 'AHI',
                       'HIMA09' : 'AHI',
                        'MVIRI' : { '1': '0.7 um',
                                    '2': '6.4 um',
                                    '3': '11.5 um'   },
                       'SEVIRI' : { '1': '0.635 um',
                                    '2': '0.81 um',
                                    '3': '1.64 um',
                                    '4': '3.92 um',
                                    '5': '6.25 um',
                                    '6': '7.35 um',
                                    '7': '8.70 um',
                                    '8': '9.66 um',
                                    '9': '10.8 um',
                                    '10': '12.0 um',
                                    '11': '13.4 um',
                                    '12': '0.7 um'},
                               'MI' :  { '5': '0.675 um', 
                                         '4': '3.75 um',
                                         '3': '6.75 um',
                                         '1': '10.8 um',
                                         '2': '12.0 um'},
                       'GOES_Imager' : { '1': '0.65 um',
                                         '2': '3.90 um',
                                         '3': '6.55 um',
                                         '4': '10.70 um',
                                         '5': '13.35 um' },
                       'MT2_Imager' :  { '5': '0.675 um', 
                                         '4': '3.75 um',
                                         '3': '6.75 um',
                                         '1': '10.8 um',
                                         '2': '12.0 um'},
                              'AHI' :  { '1': '0.455 um', 
                                         '2': '0.510 um',
                                         '3': '0.645 um',
                                         '4': '0.860 um',
                                         '5': '1.610 um',
                                         '6': '2.260 um',
                                         '7': '3.85 um',
                                         '8': '6.25 um',
                                         '9': '6.95 um',
                                        '10': '7.35 um',
                                        '11': '8.60 um',
                                        '12': '9.63 um',
                                        '13': '10.45 um',
                                        '14': '11.20 um',
                                        '15': '12.35 um',
                                        '16': '13.30 um'},
                              'ABI' :  { '1': '0.470 um', 
                                         '2': '0.640 um',
                                         '3': '0.860 um',
                                         '4': '1.380 um',
                                         '5': '1.610 um',
                                         '6': '2.260 um',
                                         '7': '3.90 um',
                                         '8': '6.15 um',
                                         '9': '7.00 um',
                                        '10': '7.40 um',
                                        '11': '8.50 um',
                                        '12': '9.70 um',
                                        '13': '10.30 um',
                                        '14': '11.20 um',
                                        '15': '12.30 um',
                                        '16': '13.30 um'}
                  } ,
           'uas': {   'sat' :  ['DMSPF16', 'DMSPF17', 'DMSPF18', 'DMSPF19', 'DMSPF20'],
                        'inst' : '186',
              'beam_positions' : int(30),
                        'freq' : {'19': '63.28+/-.29 GHz CP',
                                  '20': '60.79+/-.36 GHz CP',
                                  '21': '60.79+/-.36+/-.002 GHz CP',
                                  '22': '60.79+/-.36+/-.0055 GHz CP',
                                  '23': '60.79+/-.36+/-.016 GHz CP'   }
                                                                           } ,
           'ssmis': {    'sat' :  ['DMSPF16', 'DMSPF17', 'DMSPF18', 'DMSPF19', 'DMSPF20'],
                        'inst' : '185',
              'beam_positions' : int(30),
                        'freq' : {'1': '50.3 GHz H',
                                  '2': '52.8 GHz H',
                                  '3': '53.596 GHz H',
                                  '4': '54.4 GHz H',
                                  '5': '55.5 GHz H',
                                  '6': '57.29 GHz CP',
                                  '7': '59.4 GHz CP',
                                  '8': '150.0 GHz H',
                                  '9': '183.31+/-6.6 GHz H',
                                  '10': '183.31+/-3.0 GHz H',
                                  '11': '183.31+/-1.0 GHz H',
                                  '12': '19.35 GHz H',
                                  '13': '19.35 GHz V',
                                  '14': '22.235 GHz V',
                                  '15': '37.0 GHz H',
                                  '16': '37.0 GHz V',
                                  '17': '91.655 GHz V',
                                  '18': '91.655 GHz H',
                                  '19': '63.28+/-.29 GHz CP',
                                  '20': '60.79+/-.36 GHz CP',
                                  '21': '60.79+/-.36+/-.002 GHz CP',
                                  '22': '60.79+/-.36+/-.0055 GHz CP',
                                  '23': '60.79+/-.36+/-.016 GHz CP',
                                  '24': '60.79+/-.36+/-.050 GHz CP'   }  
                                                                           } ,
           'atms': {       'sat' : ['NPP', 'NOAA20', 'NOAA21'],
                          'inst' : '197',
                   'wmo_sat_ids' : [ 224, 225, 226 ],
                'beam_positions' : int(96),
                         'freq'  : {'1':  '23.8 GHz',
                                    '2':  '31.4 GHz',
                                    '3':  '50.3 GHz',
                                    '4':  '51.76 GHz',
                                    '5':  '52.8 GHz',
                                    '6':  '53.596+/- 0.115 GHz',
                                    '7':  '54.4 GHz',
                                    '8':  '54.94 GHz',
                                    '9':  '55.5 GHz',
                                    '10': '57.29+/-.33 GHz',
                                    '11': '57.29+/-.115+/-.078 GHz',
                                    '12': '57.29+/-.036 GHz',
                                    '13': '57.29+/-.016 GHz',
                                    '14': '57.29+/-.008 GHz',
                                    '15': '57.29+/-.003 GHz',
                                    '16': '88.2 GHz',
                                    '17': '165.5 GHz',
                                    '18': '183.31+/-7.0+/-2.0 GHz',
                                    '19': '183.31+/-4.5+/-2.0 GHz',
                                    '20': '183.31+/-3.0+/-1.0 GHz',
                                    '21': '183.31+/-1.8+/-1.0 GHz',
                                    '22': '183.31+/-1.0+/-0.5 GHz'    }
                                                                         },  
           'amsua': {    'sat' : ['NOAA15', 'NOAA16', 'NOAA18', 'NOAA19', 'METOPA','METOPB', 'METOPC'],
                 'wmo_sat_ids' : [     206,      207,      209,      223,        4,       3,        5],
                 'short_sat_ids' : [ 'n15',    'n16',    'n18',    'n19',    'mta',   'mtb',    'mtc'],
                         'inst' : '210',
              'beam_positions' : int(30),
                         'freq'  : {'1': '23.8 GHz',
                                    '2': '31.4 GHz',
                                    '3': '50.3 GHz',
                                    '4': '52.8 GHz',
                                    '5': '53.6 GHz',
                                    '6': '54.4 GHz',
                                    '7': '54.9 GHz',
                                    '8': '55.5 GHz',
                                    '9': '57.2 GHz',
                                    '10': '57.29+/-.217 GHz',
                                    '11': '57.29+/-.322+/-.048 GHz',
                                    '12': '57.29+/-.322+/-.022 GHz',
                                    '13': '57.29+/-.322+/-.010 GHz',
                                    '14': '57.29+/-.322+/-.0045 GHz',
                                    '15': '89.0 GHz'    }
                                                                         },  
           'amsub': {    'sat'  :  ['NOAA15', 'NOAA16', 'NOAA17'],
                         'inst' : '183',
              'beam_positions' : int(30),
                         'freq' : {'1': '89.0 GHz',
                                   '2': '150.0 GHz',
                                   '3': '183.31+/-1.0 GHz',
                                   '4': '183.31+/-3.0 GHz',
                                   '5': '183.31+/-7.0 GHz'   }
                                                                         },
           'mhs'  : {    'sat'  :  ['NOAA18', 'NOAA19', 'METOPA','METOPB', 'METOPC'],
                         'inst' : '184',
              'beam_positions' : int(30),
                         'freq' : {'1': '89.0 GHz',
                                   '2': '157.0 GHz',
                                   '3': '183.31+/-1.0 GHz',
                                   '4': '183.31+/-3.0 GHz',
                                   '5': '190.31 GHz'   }
                                                                         }
}
# Can easily choose an instrument subset here
# If chosen_instruments is empty, default to full_sat_sen
chosen_instruments = {}
# e.g. chosen_instruments = {'amsua','mhs','atms'}
if chosen_instruments:
    sat_sen = { key:value for key, value in full_sat_sen.items() if key in chosen_instruments}
    if not sat_sen:
        print('At least one of chosen instruments {} not found, using full sat_sen dict...'.format(chosen_instruments))
        sat_sen = full_sat_sen
else:
    sat_sen = full_sat_sen
    
